version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: cattle_health
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  mqtt:
    image: eclipse-mosquitto
    volumes:
        - mosquitto_conf:/mosquitto/config
        - mosquitto_data:/mosquitto/data
        - mosquitto_log:/mosquitto/log
    networks:
        - mqtt
    ports:
      - "9001:9001"
      - "1883:1883"
volumes:
  postgres_data:
  mosquitto_conf:
  mosquitto_data:
  mosquitto_log:
networks:
  postgres_network:
    driver: bridge
  mqtt:
    driver: bridge
